apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: payment-api
          image: javatar8soat/payment-api:latest
          ports:
            - containerPort: 8081
          env:
            - name: FASTFOOD_DATABASE_URL
              value: "jdbc:postgresql://mydb-instance.ccxwd0i0ifa8.us-east-1.rds.amazonaws.com:5432/postgres"
            - name: FASTFOOD_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: POSTGRES_USER
            - name: FASTFOOD_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: POSTGRES_PASSWORD
            - name: PAYMENT_API_HOST
              value: "https://p92ysh7yg7.execute-api.us-east-1.amazonaws.com/prod"
            - name: PAYMENT_API_PORT
              value: ""